[package]
name = "day-5-29-july"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
borsh = { version = "1.5.7", features = ["derive"] }
serde = { version = "1.0.219", fetures = ["derive"] }
serde_json = "1.0.143"
